Python environment files
rajarshd/CBR-AKBC pull request #4
Opened 2021-02-15 22:45 UTC by nirajsingh17

- Added requirements.txt file 
- Modified relative paths line#8

2021-02-15 22:52 UTC, rajarshd requested changes

2021-02-15 22:52 UTC, rajarshd commented on code/cbr.py
> -from code.data.data_utils import create_vocab, load_data, get_unique_entities, \
did you make this change because you ran it from inside the code directory? Do we still need this if we run the code from the project directory?

2021-02-15 23:04 UTC, nirajsingh17 commented on code/cbr.py
> -from code.data.data_utils import create_vocab, load_data, get_unique_entities, \
No, I am running from the project rectory but I still get this error:
`(temp) mastermind@campus-vpn-172-26-91-119 CBR-AKBC % python code/cbr.py --dataset_name FB122 --test --max_num_programs 5 --k_adj 5 --test_file_name testI.txt
Traceback (most recent call last):
  File "code/cbr.py", line 8, in <module>
    from code.data.data_utils import create_vocab, load_data, get_unique_entities, \
ModuleNotFoundError: No module named 'code.data'; 'code' is not a package
`
But on modifying line 8, it works. 
`(temp) mastermind@campus-vpn-172-26-91-119 CBR-AKBC % python code/cbr.py --dataset_name FB122 --test --max_num_programs 5 --k_adj 5 --test_file_name testI.txt
[2021-02-15 17:59:39     COMMAND: code/cbr.py --dataset_name FB122 --test --max_num_programs 5 --k_adj 5 --test_file_name testI.txt]
[2021-02-15 17:59:39     ===========FB122============]
[2021-02-15 17:59:39     Loading subgraph around entities:]
183276it [00:00, 297497.91it/s]
[2021-02-15 17:59:59     Loading train map]
183276it [00:02, 77519.86it/s] 
[2021-02-15 18:00:02     Loading dev map]
`

2021-02-15 23:15 UTC, rajarshd commented on code/cbr.py
> -from code.data.data_utils import create_vocab, load_data, get_unique_entities, \
ah ok. Did you set the pythonpath?
```cd cbr-akbc-data && export PYTHONPATH=`pwd````

2021-02-15 23:19 UTC, rajarshd commented on code/cbr.py
> -from code.data.data_utils import create_vocab, load_data, get_unique_entities, \
ah I notice the typo in my instruction, no need to cd to cbr-akbc-data.

2021-02-16 10:26 UTC, nirajsingh17 reviewed
I have reverted the change in line 8.

2021-02-22 15:15 UTC, merged